#!/usr/bin/env bash
# Regenerate STATUS.md from kanban directories, beat files, and git log.
# Called by the orchestrator during the codex-update step before each scene commit.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

count_cards() {
  if [[ -d "$1" ]]; then
    find "$1" -maxdepth 1 -type f -name '*.md' ! -name 'README.md' 2>/dev/null | wc -l | tr -d ' '
  else
    echo 0
  fi
}

count_beats() {
  local file="$1"
  [[ -f "$file" ]] || { echo 0; return; }
  awk '/^### [HS]-/ {n++} END {print n+0}' "$file"
}

count_landed() {
  # A landed beat has "**Status**: landed" — note the strict regex excludes the
  # template placeholder "**Status**: pending | landed (scene: ...)".
  local file="$1"
  [[ -f "$file" ]] || { echo 0; return; }
  awk '/^- \*\*Status\*\*: landed/ {n++} END {print n+0}' "$file"
}

pending=$(count_cards kanban/pending)
inprog=$(count_cards kanban/in-progress)
review=$(count_cards kanban/review)
done_count=$(count_cards kanban/done)

hard_total=$(count_beats codex/beats/hard.md)
hard_landed=$(count_landed codex/beats/hard.md)
soft_total=$(count_beats codex/beats/soft.md)
soft_landed=$(count_landed codex/beats/soft.md)

branch=$(git rev-parse --abbrev-ref HEAD)
now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
last_commits=$(git log --oneline -5 2>/dev/null || echo '(no commits yet)')

last_scene=$(git log --pretty=format: --name-only --diff-filter=A 2>/dev/null \
  | awk '/^books\/book-[0-9]+\/chapter-[0-9]+\/scene-[0-9]+\.md$/ {print; exit}')
last_scene=${last_scene:-none}

active=$(find kanban/in-progress -maxdepth 1 -type f -name '*.md' 2>/dev/null | head -1)
if [[ -n "$active" ]]; then
  active_label=$(basename "$active" .md)
else
  active_label=none
fi

if [[ -f .canary-approved ]]; then
  canary="yes"
else
  canary="no (first scene committed will be surfaced for sample-read)"
fi

cat > STATUS.md <<EOF
# Status

**Branch**: $branch
**Generated**: $now (UTC)

## Current state

- **Active scene**: $active_label
- **Last completed scene**: $last_scene
- **Canary scene approved**: $canary

## Kanban

| Pending | In-progress | Review | Done |
| ------- | ----------- | ------ | ---- |
| $pending | $inprog | $review | $done_count |

## Beats

| Tier | Landed | Total |
| ---- | ------ | ----- |
| Hard | $hard_landed | $hard_total |
| Soft | $soft_landed | $soft_total |

## Recent commits

\`\`\`
$last_commits
\`\`\`

---

_Regenerated by \`scripts/regen-status.sh\`. Run by the orchestrator on every scene commit._
EOF

echo "STATUS.md regenerated."
